### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by padhupradheep** [Elite-Robots/ROS#1]
Hey, we have a EC-66 arm and we are trying to connect to the robot through the ROS-Node. Unfortunately, we have the mentioned issue. We are pretty sure that the robot and the PC are in the same network. Also the remote mode is activated. I seriously doubt something is wrong with the port address, could you help us resolve this? 

We connect to the web-interface with the port 6680. 

```
new action server
[INFO] [1661844300.004924]: EliteDriver is started...
[INFO] [1661844300.006048]: JointStatePublisher is started...
[INFO] [1661844300.008739]: JointMoveService is started...
[INFO] [1661844300.010691]: ForwardKinematicService is started...
[INFO] [1661844300.012643]: InverseKinematicService is started...
[INFO] [1661844300.014648]: CartMoveService is started...
[INFO] [1661844300.016598]: RobotServoOnService is started...
[INFO] [1661844300.018597]: SetAnalogIOService is started...
[INFO] [1661844300.020497]: SetDigitalIOService is started...
[INFO] [1661844300.022523]: StopMoveService is started...
[INFO] [1661844300.024455]: RobotStatePublisher is started...
[INFO] [1661844300.026460]: JointTrajectoryMoveLService is started...
[INFO] [1661844300.028372]: JointTrajectoryMoveTService is started...
[INFO] [1661844300.032509]: Use FakeEc is False
2022-08-30 09:25:00 |Robot_IP: 10.1.30.80| DEBUG    | 10.1.30.80 connect success
2022-08-30 09:25:00 |Robot_IP: 10.1.30.80| DEBUG    | Alarm clear success
2022-08-30 09:25:00 |Robot_IP: 10.1.30.80| DEBUG    | MotorStatus sync success
2022-08-30 09:25:00 |Robot_IP: 10.1.30.80| DEBUG    | servo status set success
[INFO] [1661844300.752404]: Monitor is not start,wait...
Exception in thread Elibot monitor thread,IP:10.1.30.80:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/neobotix/.local/lib/python3.8/site-packages/elite/_monitor.py", line 144, in monitor_run
    self.__first_connect()
  File "/home/neobotix/.local/lib/python3.8/site-packages/elite/_monitor.py", line 101, in __first_connect
    sock.connect((self.robot_ip, self._PORT))
ConnectionRefusedError: [Errno 111] Connection refused
[INFO] [1661844301.757161]: Monitor is not start,wait...
[INFO] [1661844302.761086]: Monitor is not start,wait...
[INFO] [1661844303.765604]: Monitor is not start,wait...
[INFO] [1661844304.770130]: Monitor is not start,wait...
```

Best regards,
Pradheep

**Comment by Elite-Robots** [comment]
1：you need to login with administrator privileges  （password is 333333）
2：open the remote config

![image](https://user-images.githubusercontent.com/109088066/187394579-fda9c066-f502-48e0-8134-8c7f0bb8cc9c.png)

You can try again after restarting.

**Comment by padhupradheep** [comment]
The issue persists even after updating the settings. Is there anything else that we need to take care?

**Comment by padhupradheep** [comment]
That helped! Thanks!
