### ISSUE TITLE
error while sending moveit goal - not able to move the robot arm EC-66

### ISSUE THREAD

**Issue by padhupradheep** [Elite-Robots/ROS#2]
We follow the instructions to run the controller and moveit. 

While we set a goal in moveit, we are not able to move the robot arm. Under the controller.launch, we get the following log:

```
2022-08-30 13:29:53 |Robot_IP: 10.1.30.80| ERROR    | CMD: stop_push_pos |Exception: Extra data: line 2 column 1 (char 91)
==========================stop===========================
[ERROR] [1661859450.444123]: bad callback: <bound method ActionServer.internal_goal_callback of <actionlib.action_server.ActionServer object at 0x7f8a83a760a0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 523, in call
    responses = transport.receive_once()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 744, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 111, in recv_buff
    raise TransportTerminated("unable to receive data from sender, check sender's logs for details")
rospy.exceptions.TransportTerminated: unable to receive data from sender, check sender's logs for details

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/action_server.py", line 293, in internal_goal_callback
    self.goal_callback(gh)
  File "/home/neobotix/elite_ws/src/elite-robots/src/elite_controller/src/elite_controller/joint_trajectory_action.py", line 57, in on_goal

    return self.call(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 533, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details

req Stop Move
recv Stop Move
2022-08-30 13:37:30 |Robot_IP: 10.1.30.80| ERROR    | CMD: stop |Exception: Expecting value: line 1 column 1 (char 0)
[ERROR] [1661860049.079159]: bad callback: <bound method ActionServer.internal_cancel_callback of <actionlib.action_server.ActionServer object at 0x7f8a83a760a0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 523, in call
    responses = transport.receive_once()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 744, in receive_once

  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 111, in recv_buff
    raise TransportTerminated("unable to receive data from sender, check sender's logs for details")
rospy.exceptions.TransportTerminated: unable to receive data from sender, check sender's logs for details

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/action_server.py", line 238, in internal_cancel_callback
    self.cancel_callback(gh)
  File "/home/neobotix/elite_ws/src/elite-robots/src/elite_controller/src/elite_controller/joint_trajectory_action.py", line 73, in on_cancel
    self._stop_move()
  File "/home/neobotix/elite_ws/src/elite-robots/src/elite_controller/src/elite_controller/joint_trajectory_action.py", line 67, in _stop_move
    res = stop_move_client(StopMoveRequest())
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 533, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
```
did you guys face something similar?

**Comment by padhupradheep** [comment]
I think the important issue here is this line:

```2022-08-30 13:29:53 |Robot_IP: 10.1.30.80| ERROR    | CMD: stop_push_pos |Exception: Extra data: line 2 column 1 (char 91)```

**Comment by Elite-Robots** [comment]
Please let me know the robot software version
![image](https://user-images.githubusercontent.com/109088066/187503718-eff16f6d-cbe7-4abb-ad06-1a4220822d15.png)

**Comment by padhupradheep** [comment]
Controller Software: It's V3.3.2.2022061

Servo Software: V11.39

**Comment by padhupradheep** [comment]
I can see from your image that, the version of the controller software is different from the one that we use. Could that be the one causing the issue?

**Comment by padhupradheep** [comment]
updating the controller software fixed the issue. Thanks for the nice support Elite.
