### ISSUE TITLE
TypeError: must be real number, not NoneType

### ISSUE THREAD

**Issue by Destinycjk** [Elite-Robots/ROS#7]
Hello!
I cloned this repository and ran with Ubuntu 20.04.5 LTS and ROS Noetic installed.
I tried to command an EC66 robot with the following firmware and software versions:
Controller software V2.2.4.20210330

I have connected to EC66. When I ran the order " roslaunch elite_controller elite_controller.launch robot:=ec66 robot_ip:=192.168.1.200", it failed with clue "TypeError: must be real number, not NoneType". The complete log is listed below:
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://chenkai-FX503VD:42549/

SUMMARY
========

PARAMETERS
 * /elite_controller/interpolate_sample_time: 0.008
 * /elite_controller/trajectory_service_name: joint_trajectory_...
 * /elite_driver/auto_connect: True
 * /elite_driver/ip_address: 192.168.1.200
 * /elite_driver/joint_name: ['joint1', 'joint...
 * /elite_driver/loop_rate: 125
 * /elite_driver/use_fake: False
 * /rosdistro: noetic
 * /rosversion: 1.15.14

NODES
  /
    elite_controller (elite_controller/elite_controller_node.py)
    elite_driver (elite_driver/elite_driver_node.py)

auto-starting new master
process[master]: started with pid [41278]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to e9ac95ac-5abf-11ed-be9a-c1a52c90ddcd
process[rosout-1]: started with pid [41288]
started core service [/rosout]
process[elite_controller-2]: started with pid [41295]
process[elite_driver-3]: started with pid [41296]
new action server
[INFO] [1667401583.382011]: EliteDriver is started...
[INFO] [1667401583.386731]: JointStatePublisher is started...
[INFO] [1667401583.396485]: JointMoveService is started...
[INFO] [1667401583.402813]: ForwardKinematicService is started...
[INFO] [1667401583.407737]: InverseKinematicService is started...
[INFO] [1667401583.412686]: CartMoveService is started...
[INFO] [1667401583.417707]: RobotServoOnService is started...
[INFO] [1667401583.422801]: SetAnalogIOService is started...
[INFO] [1667401583.428155]: SetDigitalIOService is started...
[INFO] [1667401583.433487]: StopMoveService is started...
[INFO] [1667401583.442905]: RobotStatePublisher is started...
[INFO] [1667401583.449467]: JointTrajectoryMoveLService is started...
[INFO] [1667401583.454386]: JointTrajectoryMoveTService is started...
[INFO] [1667401583.465680]: Use FakeEc is False
2022-11-02 23:06:23 |Robot_IP: 192.168.1.200| DEBUG    | 192.168.1.200 connect success
2022-11-02 23:06:23 |Robot_IP: 192.168.1.200| WARNING  | CMD: clearAlarm | Failed to clear alarm, invalid force
2022-11-02 23:06:23 |Robot_IP: 192.168.1.200| DEBUG    | Alarm clear success
2022-11-02 23:06:23 |Robot_IP: 192.168.1.200| DEBUG    | MotorStatus sync success
2022-11-02 23:06:24 |Robot_IP: 192.168.1.200| DEBUG    | servo status set success
[INFO] [1667401584.086179]: Monitor is not start,wait...
[INFO] [1667401585.090794]: Robot startup success...
Traceback (most recent call last):
  File "/home/chenkai/catkin_ws/ROS/devel/lib/elite_driver/elite_driver_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/chenkai/catkin_ws/ROS/src/elite_driver/scripts/elite_driver_node.py", line 27, in <module>
    main()
  File "/home/chenkai/catkin_ws/ROS/src/elite_driver/scripts/elite_driver_node.py", line 22, in main
    elite_driver.spin()
  File "/home/chenkai/catkin_ws/ROS/src/elite_driver/src/elite_driver/elite_driver.py", line 82, in spin
    JointStatePublisher.spin(self)
  File "/home/chenkai/catkin_ws/ROS/src/elite_driver/src/elite_driver/joint_states.py", line 33, in spin
    self.update_joint_state()
  File "/home/chenkai/catkin_ws/ROS/src/elite_driver/src/elite_driver/joint_states.py", line 49, in update_joint_state
    self.joint_state_.velocity.append(math.radians(speed))
TypeError: must be real number, not NoneType
[elite_driver-3] process has died [pid 41296, exit code 1, cmd /home/chenkai/catkin_ws/ROS/devel/lib/elite_driver/elite_driver_node.py __name:=elite_driver __log:=/home/chenkai/.ros/log/e9ac95ac-5abf-11ed-be9a-c1a52c90ddcd/elite_driver-3.log].
log file: /home/chenkai/.ros/log/e9ac95ac-5abf-11ed-be9a-c1a52c90ddcd/elite_driver-3*.log

I don't know where it wrongs. Could you help me?

**Comment by miaokeqin** [comment]
Upgrade the software version. Best version > =3.5
